Update build-test.yml

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -19,7 +19,7 @@ jobs:
     - name: Make and run tests
       run: make test
     - name: Check tests
-      run: if grep -q FAIL build/results/test_info.txt; then echo "::error::At least 1 test failed"; fi
+      run: if grep -q FAIL build/results/test_info.txt; then echo "::error::At least 1 test failed", exit 1; fi
     - name: Get coverage report
       run: sudo .github/scripts/get_code_cov.sh
     - name: Upload coverage report to Codecov 
@@ -28,5 +28,3 @@ jobs:
         flags: unittest
         fail_ci_if_error: true
         verbose: true
-    - name: The job has succeeded
-      if: ${{ success() }}
